### ISSUE TITLE
Does not compile - multiple definition of Debug,Handle,LastSyscall and DebugStats

### ISSUE THREAD

**Issue by zapp42** [spieglt/whatfiles#1]
This is on Fedora Rawhide with gcc-10.1.1:
gcc -Wall -o bin/whatfiles src/whatfiles.c src/attach.c src/utilities.c src/hashmap.c src/strings.c
/usr/bin/ld: /tmp/ccQ3yzmx.o:(.bss+0x0): multiple definition of `DebugStats'; /tmp/ccU4Rmdu.o:(.bss+0x0): first defined here
/usr/bin/ld: /tmp/ccQ3yzmx.o:(.bss+0x8): multiple definition of `Debug'; /tmp/ccU4Rmdu.o:(.bss+0x8): first defined here
/usr/bin/ld: /tmp/ccQ3yzmx.o:(.bss+0x10): multiple definition of `Handle'; /tmp/ccU4Rmdu.o:(.bss+0x10): first defined here
/usr/bin/ld: /tmp/ccQ3yzmx.o:(.bss+0x20): multiple definition of `LastSyscall'; /tmp/ccU4Rmdu.o:(.bss+0x20): first defined here
/usr/bin/ld: /tmp/ccYoBtdu.o:(.bss+0x0): multiple definition of `DebugStats'; /tmp/ccU4Rmdu.o:(.bss+0x0): first defined here
/usr/bin/ld: /tmp/ccYoBtdu.o:(.bss+0x8): multiple definition of `Debug'; /tmp/ccU4Rmdu.o:(.bss+0x8): first defined here
/usr/bin/ld: /tmp/ccYoBtdu.o:(.bss+0x10): multiple definition of `Handle'; /tmp/ccU4Rmdu.o:(.bss+0x10): first defined here
/usr/bin/ld: /tmp/ccYoBtdu.o:(.bss+0x20): multiple definition of `LastSyscall'; /tmp/ccU4Rmdu.o:(.bss+0x20): first defined here
/usr/bin/ld: /tmp/ccUyQNjw.o:(.bss+0x0): multiple definition of `DebugStats'; /tmp/ccU4Rmdu.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status

The problem is that you define those variables in an include file and everywhere this file gets included, the variable is defined again. See variable definition vs. declaration here: https://stackoverflow.com/questions/19326789/variable-declaration-vs-definition.

**Comment by spieglt** [comment]
Thanks @zapp42, I had originally tried to say `int Debug` in the header and `Debug = 0` in the file which didn't work, didn't know I needed to use `extern`. Any idea why it compiled fine on my Mint 19 machine?

**Comment by zapp42** [comment]
Mint19 has gcc-7.3 and binutils-2.30 while Fedora is on gcc-10.1 and binutils-2.34. Warnings and error messages tend to increase with each version, so this might be it.
