### ISSUE TITLE
Will it be a version release for packaging? 

### ISSUE THREAD

**Issue by jetm** [spieglt/whatfiles#3]
Thank you for this great tool.

I am interested in creating an Arch Linux package. Will it be a version release?

**Comment by spieglt** [comment]
Hi, I think someone's already done that! https://aur.archlinux.org/packages/whatfiles-git/ But thank you for offering to do so. I do need to put a version tag on it somewhere though I don't have a lot of features planned right now.

**Comment by letompouce** [comment]
For what it's worth, I created a [GitLab CICD Pipeline](https://gitlab.com/l3tompouce/builders/whatfiles) to build the binary, which is kept as an artifact for easy download.

Makes it easy to install via `wget && chmod`, integrate in an Ansible playbook, etc.

**Comment by spieglt** [comment]
@letompouce thank you for doing that! My first reaction was "what about library incompatibilities in different versions of different distros?" before I remembered... it doesn't really use any libraries, hah. Should be pretty portable. Maybe I should mention the Arch package and this GitLab pipeline in the readme, and just make a binary release on the main repo as well?
```
$ ldd `which whatfiles`
        linux-vdso.so.1 (0x00007ffe109af000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5b96287000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5b96880000)
```

**Comment by letompouce** [comment]
Well, I see that since you wrote that, you did a Relase, and also added these external contributions to the README (2c4f12fb230a803f08a71bc8995adb101c31c3fe).

I guess the next stop would be to add GitHub Actions to take care of the build automatically ; from then, maybe someone will contribute more Actions to build `.deb`/`.rpm`/whatnot packages builds as well! :-)

**Comment by letompouce** [comment]
Oh, and I now realise I would have an use for this tool on i386 architectures as well :grin:

**Comment by spieglt** [comment]
@letompouce It's easy enough to build, and changes infrequently enough that I probably won't go to the trouble of GitHub Actions. I don't currently have any major plans for this program unless people request more features or find problems. And if people would like to add it to RPM or Debian, which I would greatly appreciate, they should be able to do so with the source or binaries already, right?

As for i386, what distro and version would you be using it with? I'd normally reach for Ubuntu but they stopped releasing it. I don't have any x86 machines, but I think I'd be able to boot a 32-bit live disk on any of my x64 machines and figure it out that way. That's basically what I did for the 32-bit ARM version.

**Comment by letompouce** [comment]
Yeah, I'm fine with the `wget && chmod` packaging system! \o/

I'd like to use `whatfiles` on a IoT device which runs Ubuntu 16.04 32 bits. My C-related skills are limited to adding a `-m32` flag :p

**Comment by spieglt** [comment]
Cool, might take me a while but I'll give it a shot at some point.

**Comment by spieglt** [comment]
@letompouce There's an x86 version compiled on Ubuntu 16 on the [releases](https://github.com/spieglt/whatfiles/releases) page! Please let me know whether it works.

**Comment by letompouce** [comment]
Works like a charm, many thanks!
