### ISSUE TITLE
deletion of process from hashmap failed

### ISSUE THREAD

**Issue by muralikodali** [spieglt/whatfiles#4]
on every command executed, whatfiles is exiting with "deletion of {process id} from hashmap failed"  after successfully showing all needed information as below;

```
exited 18896 at entry to syscall
deletion of 18896 from hashmap failed
all children exited
```

**Comment by spieglt** [comment]
Only when running with the debug (`-d`) flag, right? That's not a problem, just means that `whatfiles` wasn't aware that the process had been exec'd/forked/cloned and didn't have a record of it. I'm still not sure why this happens in all cases but continuing to experiment and I've adjusted some of the debug output to be more clear. "all children exited" is the normal exit message. Thank you for the feedback!
