### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [spieglt/whatfiles#5]
[An extra null pointer check is not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [destroy](https://github.com/spieglt/whatfiles/blob/dac226fd30a76537b9b1fff3910acb7b47f22a5c/src/hashmap.c#L96 "destroy function")
- [init_string](https://github.com/spieglt/whatfiles/blob/dac226fd30a76537b9b1fff3910acb7b47f22a5c/src/strings.c#L8 "init_string function")

**Comment by spieglt** [comment]
Thank you, just fixed. Thought that was dangerous for some reason.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/spieglt/whatfiles/commit/c0dfcbfce1cf1c2d9248a31d8173a2499baa82df "Deletion of three redundant checks").
