### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [spieglt/whatfiles#6]
I suggest to reuse a higher level build system than [your current small make script](https://github.com/spieglt/whatfiles/blob/dac226fd30a76537b9b1fff3910acb7b47f22a5c/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by spieglt** [comment]
I avoided that because I like the simplicity of the current makefile and `whatfiles` has no dependencies or large features planned currently. Can you give me any idea of what the benefits would be for this project specifically?

**Comment by elfring** [comment]
- Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.18/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?

**Comment by spieglt** [comment]
Maybe I still don't understand, but `autoscan` just shows `AC_CHECK_HEADERS([fcntl.h stddef.h stdlib.h string.h unistd.h])` and for better or worse this project is pretty Linux-specific, so I feel comfortable requiring `make` and `gcc` to work with it (though `clang` can easily be swapped out in the makefile). If I make a cross-platform C project, however, I'll almost certainly use CMake. Danke für deine Hilfe!
