### ISSUE TITLE
Does not compile on Raspbian (stretch) on RpI B+

### ISSUE THREAD

**Issue by nenad-sladojevic** [spieglt/whatfiles#7]
pi@slade-pi-1b:~ $ uname -a
Linux slade-pi-1b 4.19.66+ #1253 Thu Aug 15 11:37:30 BST 2019 armv6l GNU/Linux
pi@slade-pi-1b:~ $ make --version
GNU Make 4.1
pi@slade-pi-1b:~ $ gcc --version
gcc (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516
pi@slade-pi-1b:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
pi@slade-pi-1b:~ $ git clone https://github.com/spieglt/whatfiles.git
...
✔ ~/whatfiles [master|✔]
20:02 $ make
gcc -Wall -o bin/whatfiles src/whatfiles.c src/attach.c src/utilities.c src/hashmap.c src/strings.c
src/whatfiles.c:22:46: warning: ‘struct user_regs_struct’ declared inside parameter list will not be visible outside of this definition or declaration
 void check_syscall(pid_t current_pid, struct user_regs_struct regs, HashMap map)
                                              ^~~~~~~~~~~~~~~~
src/whatfiles.c:22:63: error: parameter 2 (‘regs’) has incomplete type
 void check_syscall(pid_t current_pid, struct user_regs_struct regs, HashMap map)
                                                               ^~~~
src/whatfiles.c: In function ‘step_syscall’:
src/whatfiles.c:164:29: error: storage size of ‘regs’ isn’t known
     struct user_regs_struct regs;
                             ^~~~
src/whatfiles.c:164:29: warning: unused variable ‘regs’ [-Wunused-variable]
src/utilities.c: In function ‘peek_filename’:
src/utilities.c:78:18: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     long *addr = (long*)p_reg;
                  ^
Makefile:8: recipe for target 'bin/whatfiles' failed
make: *** [bin/whatfiles] Error 1
✘-2 ~/whatfiles [master|✔]

Let me know if you need any additional information.

**Comment by spieglt** [comment]
So I was looking into that error thinking it was due to the `gcc` version being different or some such, and was looking up how to virtualize Raspbian on my Linux machine when I realized that it's an ARM architecture and my machines are x86_64 (AMD64, whatever). So I think it's complaining because the `user_regs_struct` type isn't present or isn't the same on Linux compiled for ARM.

In other words, `whatfiles` currently only runs on x86_64 processors, so supporting any Raspberry Pi would require substantial changes. I don't have a Pi but have wanted one so might order. I also think I can emulate it with QEMU. But not sure when I'd get around to any of this to be honest. I'll add the limitation to the readme, thanks!

**Comment by spieglt** [comment]
Closing for now, but for future reference, the file that exposes `ptrace` functionality for ARM64 is https://github.com/torvalds/linux/blob/master/arch/arm64/include/uapi/asm/ptrace.h. And seems like the necessary information about syscalls on ARM64 Linux is available here: https://chromium.googlesource.com/chromiumos/docs/+/master/constants/syscalls.md#arm64-64_bit.

**Comment by spieglt** [comment]
@nenad-sladojevic would you please checkout the `ARM` branch and see if it works for you? Seems to be working on my Raspberry Pi 4.

**Comment by spieglt** [comment]
I was wrong about anything 64-bit being relevant. Though my RPi4 has a 64-bit processor, it runs in 32-bit mode for Raspbian so the ARM branch as written uses the 32-bit registers and should work on all Raspberry Pis.

**Comment by spieglt** [comment]
I also just fixed an error in the Makefile that would've prevented it from compiling for you. My `uname -m` output is `armv7l` and yours is `armv6l`. It should now compile for ARM32 on machines whose `uname -m` output includes the substring `arm`. Also I've merged it all to master so no need to checkout the ARM branch.

**Comment by nenad-sladojevic** [comment]
Hello,
It now compiles and runs just fine on my RPi 1 B+
✔ ~/whatfiles [ARM|✔]
20:45 $ make
gcc -Wall -o bin/whatfiles src/whatfiles.c src/attach.c src/utilities.c src/hashmap.c src/strings.c src/arm32/registers.c
✔ ~/whatfiles [ARM|✔]
20:45 $ sudo make install
cp ./bin/whatfiles /usr/local/bin/whatfiles

Thank you for your work!

One question:
When I attach to a process (with sudo whatfiles -p 1234), how do I stop the monitoring ?

**Comment by spieglt** [comment]
Great to hear! Thank you for following up. To exit just hit Ctrl-C or otherwise send it SIGINT or SIGTERM.
